version: '3.7'

services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
  server:
    build: interstellar-backend
    image: interstellar/backend
    ports:
      - '3000:3000'
    links:
      - mongo-db
  client:
    build: interstellar-frontend
    image: interstellar/frontend
    ports:
      - '4200:80'